services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo:27017/airbnb_clone
      CLIENT_ORIGIN: http://localhost:4000
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
